add eye tracker tags
cpp-lln-lab/localizer_visual_motion pull request #63
Opened 2020-09-30 15:23 UTC by marcobarilari

to be tested with the eyetracker if it actually work but you can review the 'code style'

2020-09-30 16:10 UTC, Remi-Gau requested changes
I suspect that some those things might not work. 

Let's check again after you test it tomorrow.

2020-09-30 16:10 UTC, Remi-Gau commented on visualLocTranslational.m
> +        eyeTracker('Message', cfg, ['start_block-', iBlock]);
```suggestion
        eyeTracker('Message', cfg, ['start_block-', num2str(iBlock)]);
```

2020-09-30 16:10 UTC, Remi-Gau commented on visualLocTranslational.m
> +            eyeTracker('Message', cfg, ['start_trial-', iEvent, '_', thisEvent]);
I think you will have a problem there, no?

iEvent is an `integer` and `thisEvent` is a structure so concatenating those will throw an error, no?

2020-09-30 16:10 UTC, Remi-Gau commented on visualLocTranslational.m
> +        eyeTracker('Message', cfg, ['end_trial-', iEvent, '_', thisEvent]);
same as above

2020-09-30 18:56 UTC, marcobarilari commented on visualLocTranslational.m
> +        eyeTracker('Message', cfg, ['start_block-', iBlock]);
yes, good point

2020-09-30 19:13 UTC, marcobarilari commented
definitely, I was too fast to call the game over. Now it should be fine

2020-09-30 19:16 UTC, marcobarilari commented
an extra thing that I would ask you to double-check is whether those messages are in the correct place in the script (exp-time and code congruency)

2020-09-30 20:00 UTC, marcobarilari commented
cpp-lln-lab/CPP_PTB#84 is linked

2020-10-01 14:26 UTC, Remi-Gau approved these changes
Good to go.

Merge whenever you want.

2020-10-01 14:29 UTC, merged